basePath: /
definitions:
  controllers.APIResponse:
    properties:
      details:
        $ref: '#/definitions/controllers.WalletDetails'
      message:
        example: User wallet details found.
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.ContestInfo:
    properties:
      contest_amount:
        example: 10000
        type: integer
      contest_date:
        example: "2024-12-21T18:00:00+05:30"
        type: string
      contest_id:
        example: 1
        type: integer
      contest_name:
        example: GK
        type: string
    type: object
  controllers.JoinContestResponse:
    properties:
      message:
        example: Contest joined successfully.
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.JoinedContestResponse:
    properties:
      details:
        items:
          $ref: '#/definitions/controllers.ContestInfo'
        type: array
      message:
        example: Contest list found.
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.OTPResponse:
    properties:
      details:
        properties:
          otp:
            example: "8162"
            type: string
          userId:
            example: 3
            type: integer
        type: object
      message:
        example: New user created
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.Question:
    properties:
      category_id:
        example: 1
        type: integer
      correct_answer:
        example: c
        type: string
      created_at:
        example: "2024-12-18T14:16:53+05:30"
        type: string
      id:
        example: 1
        type: integer
      level:
        example: easy
        type: string
      option_a:
        example: Unites States of America
        type: string
      option_b:
        example: England
        type: string
      option_c:
        example: India
        type: string
      option_d:
        example: Sri Lanka
        type: string
      question:
        example: Where is Delhi?
        type: string
    type: object
  controllers.QuizResponse:
    properties:
      details:
        properties:
          category_id:
            example: 1
            type: integer
          category_name:
            example: GK
            type: string
          questions:
            items:
              $ref: '#/definitions/controllers.Question'
            type: array
          questions_duration:
            example: 60
            type: integer
          quiz_end_time:
            example: "2024-12-24T18:57:33+05:30"
            type: string
          quiz_start_time:
            example: "2024-12-24T14:00:00+05:30"
            type: string
        type: object
      message:
        example: Quiz question list found.
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.Transaction:
    properties:
      amount:
        example: 20
        type: number
      created:
        example: "2024-12-18T23:04:50+05:30"
        type: string
      title:
        example: Deposit
        type: string
      transaction_type:
        example: CREDIT
        type: string
    type: object
  controllers.WalletDetails:
    properties:
      transactions:
        items:
          $ref: '#/definitions/controllers.Transaction'
        type: array
      wallet:
        type: number
    type: object
  controllers.categoryInfo:
    properties:
      details:
        items:
          properties:
            active:
              example: "1"
              type: string
            created:
              example: "2024-12-17T18:07:19+05:30"
              type: string
            icon:
              example: https://quizbuck.s3.ap-south-1.amazonaws.com/uploads/1734090491_new.jpg
              type: string
            id:
              example: 1
              type: integer
            join_amount:
              example: 100
              type: integer
            num_of_users_can_join:
              example: 20
              type: integer
            num_of_users_have_joined:
              example: 0
              type: integer
            quiz_time:
              example: "2024-12-17T18:00:00+05:30"
              type: string
            title:
              example: GK
              type: string
            total_price:
              example: 100000
              type: integer
            user_has_joined:
              example: true
              type: boolean
          type: object
        type: array
      message:
        example: Category list data found.
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.editProfileResponse:
    properties:
      message:
        example: User info updated successfully.
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.fileUploadResponse:
    properties:
      details:
        properties:
          url:
            example: https://quizbuck.s3.ap-south-1.amazonaws.com/uploads/1734090491_new.jpg
            type: string
        type: object
      message:
        example: File uploaded successfully
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.transactionResponse:
    properties:
      message:
        example: Transaction successful and user wallet updated.
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.userInfo:
    properties:
      details:
        properties:
          ID:
            example: 3
            type: integer
          created:
            example: "2024-12-10T07:04:37Z"
            type: string
          email:
            example: shivam@gmail.com
            type: string
          name:
            example: Shivam
            type: string
          otp:
            example: "8162"
            type: string
          phone:
            example: "9144"
            type: string
          register:
            example: "1"
            type: string
        type: object
      message:
        example: User logged in successfully
        type: string
      status:
        example: "1"
        type: string
    type: object
  controllers.verifyOtpResponse:
    properties:
      details:
        properties:
          ID:
            example: 3
            type: integer
          created:
            example: "2024-12-10T07:04:37Z"
            type: string
          email:
            example: shivam@gmail.com
            type: string
          name:
            example: Shivam
            type: string
          otp:
            example: "8162"
            type: string
          phone:
            example: "9144"
            type: string
          register:
            example: "1"
            type: string
        type: object
      message:
        example: User logged in successfully
        type: string
      status:
        example: "1"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is list API's to be used in Quiz App.
  termsOfService: http://swagger.io/terms/
  title: Quiz App API's
  version: "1.0"
paths:
  /quizes/get-categories/{user_id}:
    get:
      consumes:
      - application/json
      description: This API will provide list of quiz categories
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.categoryInfo'
      summary: This API will provide list of quiz categories
      tags:
      - Quizes
  /quizes/get-contest-joined-by-user/{user_id}:
    get:
      consumes:
      - application/json
      description: This API will list contest joined by user
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.JoinedContestResponse'
      summary: This API will list contest joined by user
      tags:
      - Quizes
  /quizes/get-question-by-category/{category_id}:
    get:
      consumes:
      - application/json
      description: This API will provide list of quiz questions
      parameters:
      - description: quiz category id
        in: path
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.QuizResponse'
      summary: This API will provide list of quiz questions
      tags:
      - Quizes
  /quizes/user-join-contest:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: This API will make user to join a contest
      parameters:
      - description: user id
        in: formData
        name: user_id
        required: true
        type: integer
      - description: quiz category id
        in: formData
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.JoinContestResponse'
      summary: This API will make user to join a contest
      tags:
      - Quizes
  /upload/file:
    post:
      consumes:
      - application/json
      description: upload file to s3
      parameters:
      - description: user file to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.fileUploadResponse'
      summary: upload file to s3
      tags:
      - User AUth
  /users/check-user/{phone}:
    get:
      consumes:
      - application/json
      description: generateing OTP for the user
      parameters:
      - description: user phone number
        in: path
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.OTPResponse'
      summary: generateing OTP for the user
      tags:
      - User AUth
  /users/edit-user-profile:
    post:
      consumes:
      - multipart/form-data
      description: This API edits the user profile
      parameters:
      - description: User ID
        in: formData
        name: id
        required: true
        type: string
      - description: User Name
        in: formData
        name: name
        required: true
        type: string
      - description: User Email
        in: formData
        name: email
        required: true
        type: string
      - description: User Phone
        in: formData
        name: phone
        required: true
        type: string
      - description: User Image
        in: formData
        name: image
        required: true
        type: string
      - description: User Gender (Male, Female, Others)
        in: formData
        name: gender
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.editProfileResponse'
      summary: This API edits the user profile
      tags:
      - User Auth
  /users/get-user-wallet-details/{user_id}:
    get:
      consumes:
      - application/json
      description: Fetches user wallet and transaction details
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.APIResponse'
      summary: Get user wallet details
      tags:
      - User Wallet
  /users/get-user/{id}:
    get:
      consumes:
      - application/json
      description: This API will provide user info bu id
      parameters:
      - description: this is user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.userInfo'
      summary: This API will provide user info bu id
      tags:
      - User AUth
  /users/initiate-user-transaction:
    post:
      consumes:
      - multipart/form-data
      description: This API will make user transactions
      parameters:
      - description: User ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: Transaction Amount
        in: formData
        name: amount
        required: true
        type: number
      - description: Transaction Type (CREDIT/DEBIT)
        in: formData
        name: transaction_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.transactionResponse'
      summary: This API will make user transactions
      tags:
      - User Wallet
  /users/verify-otp/{userId}/{otp}:
    get:
      consumes:
      - application/json
      description: This API will verify user OTP with userId
      parameters:
      - description: user app Id
        in: path
        name: userId
        required: true
        type: string
      - description: user otp
        in: path
        name: otp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.verifyOtpResponse'
      summary: This API will verify user OTP with userId
      tags:
      - User AUth
swagger: "2.0"
